CC = clang
CFLAGS = -Wall -Wextra -fPIC -I.
TARGET_DIR = bin
TARGET = libcerverus.so
SRC_DIR = lib
SRCS = $(shell find $(SRC_DIR) -type f -name "*.c")

$(TARGET): $(SRCS)
	mkdir -p $(TARGET_DIR)
	$(CC) -shared $(CFLAGS) -o $(TARGET_DIR)/$(TARGET) $(SRCS)