CC = clang
CFLAGS = -Wall -Wextra -I./lib
LDFLAGS = -L./bin -lcerverus
TARGET_DIR = bin/server
TARGET = server
SRC_DIR = server/src
SRCS = $(shell find $(SRC_DIR) -type f -name "*.c")

.PHONY: $(TARGET)

$(TARGET): $(SRCS)
	mkdir -p $(TARGET_DIR)
	$(CC) $(CFLAGS) -o $(TARGET_DIR)/$(TARGET) $(SRCS) $(LDFLAGS)